### ISSUE TITLE
Support for running on Windows with WSL

### ISSUE THREAD

**Issue by silasary** [yourbase/yourbase-vscode#1]
`yb` isn't available on Windows, and the documentation seems to recommend installing it via WSL.  
This works, but it means the command to run it is `wsl yb` rather than `yb`.  

As far as I can tell, the extension doesn't have any way to configure it to use an alternate command for `yb`

**Comment by zombiezen** [comment]
Interesting! Making sure I understand here: you want to build a project from a local Windows install (not using the [Remote WSL extension](https://code.visualstudio.com/docs/remote/wsl)), but have the build run inside WSL? That seems pretty do-able: the only trick is to make sure the configuration setting is [scoped to `machine`](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration).

I can try to get to this in the next few weeks. Otherwise, happy to accept a PR for this!

**Comment by zombiezen** [comment]
This has been released in [v0.3.0](https://github.com/yourbase/yourbase-vscode/releases/tag/v0.3.0) of the extension. Let me know if you encounter any issues.
